import { useEffect, useState } from "react";
import "./App.css";
import PatientInfo from "./components/PatientInfo";
import TestResultsTable from "./components/TestResultsTable";
import DoctorNotes from "./components/DoctorNotes";

function App() {
  const [report, setReport] = useState(null);

  useEffect(() => {
    fetch("/report.json")
      .then((res) => res.json())
      .then(setReport)
      .catch((err) => console.error("Failed to load report:", err));
  }, []);

  useEffect(() => {
    console.log("Report loaded:", report);
  }, [report]);

  if (!report) return <p className="p-4">Loading report…</p>;

  return (
    <div className="container mx-auto max-w-3xl p-4 text-foreground font-sans">
      <h1 className="text-3xl font-bold mb-6">Medical Laboratory Report</h1>
      <PatientInfo info={report.patient_info} />
      <TestResultsTable results={report.test_results} />
      <DoctorNotes notes={report.doctor_notes} />
      <footer className="mt-8 text-center text-sm text-muted-foreground">
        <em>Report generated by Acme Medical Labs</em>
      </footer>
    </div>
  );
}

export default App;
