import { useEffect, useState } from "react";
import "./App.css";
import PatientInfo from "./components/PatientInfo";
import TestResultsTable from "./components/TestResultsTable";
import DoctorNotes from "./components/DoctorNotes";

function App() {
  const [report, setReport] = useState(null);

  useEffect(() => {
    fetch("/report.json")
      .then((res) => res.json())
      .then(setReport)
      .catch((err) => console.error("Failed to load report:", err));
  }, []);

  useEffect(() => {
    console.log("Report loaded:", report);
  }, [report]);

  if (!report) return <p>Loading report…</p>;

  return (
    <div
      style={{ fontFamily: "Arial, sans-serif", padding: 20, color: "#333" }}
    >
      <h1>Medical Laboratory Report</h1>
      <PatientInfo info={report.patient_info} />
      <TestResultsTable results={report.test_results} />
      <DoctorNotes notes={report.doctor_notes} />
      <footer
        style={{
          marginTop: 40,
          fontSize: "0.9em",
          textAlign: "center",
          color: "#666",
        }}
      >
        <em>Report generated by Acme Medical Labs</em>
      </footer>
    </div>
  );
}

export default App;
